# Download data from kaggle

In [3]:
!rm -rf sample_data

In [4]:
!pip install -q kaggle

In [5]:
!mkdir ~/.kaggle

The syntax of the command is incorrect.

In [6]:
!cp kaggle.json ~/.kaggle/

cp: cannot stat 'kaggle.json': No such file or directory

In [7]:
!chmod 600 ~/.kaggle/kaggle.json

chmod: cannot access '~/.kaggle/kaggle.json': No such file or directory

In [8]:
!kaggle competitions download -c house-prices-advanced-regression-techniques

Traceback (most recent call last):
  File "C:\Users\USER\anaconda3\envs\min_ds-env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\anaconda3\envs\min_ds-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\anaconda3\envs\min_ds-env\Scripts\kaggle.exe\__main__.py", line 4, in <module>
  File "C:\Users\USER\anaconda3\envs\min_ds-env\lib\site-packages\kaggle\__init__.py", line 23, in <module>
    api.authenticate()
  File "C:\Users\USER\anaconda3\envs\min_ds-env\lib\site-packages\kaggle\api\kaggle_api_extended.py", line 164, in authenticate
    raise IOError('Could not find {}. Make sure it\'s located in'
OSError: Could not find kaggle.json. Make sure it's located in C:\Users\USER\.kaggle. Or use the environment method.

# Explore data

In [11]:
import pandas as pd

train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')
print("Train size: ", train_df.shape)
print("Test size: ", test_df.shape)
train_df.head()

Train size:  (1460, 81)
Test size:  (1459, 80)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [12]:
#print null columns from the training file
train_df[train_df.isnull().any(axis=1)]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [13]:
#print info of the training file
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [14]:
#print total null values of each columns
pd.set_option('display.max_columns', None)  
pd.set_option('display.max_rows', None)  
train_df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [15]:
#get some info about saleprice
train_df['SalePrice'].describe()

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

# Preprocess data

In [16]:
import numpy as np

#use log1p to SalePrice column to avoid inf values from log(0)
train_df['SalePrice'] = np.log1p(train_df['SalePrice'])

In [17]:
Y_train = train_df['SalePrice']
#merge two table of the training and testing file to preprocess
all_data = pd.concat([train_df, test_df], axis = 0, sort = False)
all_data = all_data.drop(['Id', 'SalePrice'], axis = 1)

In [ ]:
Total = all_data.isnull().sum().sort_values(ascending = False)
missing_data = pd.DataFrame(Total).rename(columns={0: "Total missing"})
missing_data

In [11]:
#drop columns which have total missing data > 5 and columns with max total missing are 4
all_data.drop((missing_data[missing_data['Total missing'] > 5]).index, axis = 1, inplace = True)

In [12]:
all_data.isnull().sum().sort_values().tail()

Utilities       2
Functional      2
BsmtFullBath    2
BsmtHalfBath    2
MSZoning        4
dtype: int64

In [13]:
print('Categorical columns:', all_data.select_dtypes(include=['object']).columns)
print('Numeric columns:', all_data.select_dtypes(exclude=['object']).columns)

Categorical columns: Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional',
       'PavedDrive', 'SaleType', 'SaleCondition'],
      dtype='object')
Numeric columns: Index(['MSSubClass', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt',
       'YearRemodAdd', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'TotRmsAbvGrd', 'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold'],
      dtype='object')

In [14]:
#need check BsmtFullBath and BsmtHalfBath
numeric_missing_columns = ['BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'GarageArea', 'GarageCars']
for val in numeric_missing_columns:
    all_data[val] = all_data[val].fillna(0)
categorical_missing_columns = ['Exterior1st', 'Exterior2nd', 'SaleType', 'MSZoning', 'Electrical', 'KitchenQual']                   
for val in categorical_missing_columns:
    all_data[val] = all_data[val].fillna(all_data[val].mode()[0])

In [15]:
all_data['Functional'] = all_data['Functional'].fillna('Typ')
#all values of Utilities column are the same, so we should delete it
all_data.drop(['Utilities'], axis=1, inplace=True) 
all_data.isnull().sum().max() #no more missing columns

0

In [16]:
from scipy.stats import skew

numeric_features = all_data.dtypes[all_data.dtypes != 'object'].index
skewed_features = all_data[numeric_features].apply(lambda x: skew(x)).sort_values()
#get all columns with skewness > 0.5 and make log transformation on them
col_skewness = skewed_features[abs(skewed_features) > 0.5]
col_skewness

YearBuilt        -0.599806
OverallCond       0.570312
BsmtFullBath      0.624832
HalfBath          0.694566
Fireplaces        0.733495
TotRmsAbvGrd      0.758367
2ndFlrSF          0.861675
BsmtUnfSF         0.919339
TotalBsmtSF       1.156894
GrLivArea         1.269358
MSSubClass        1.375457
BsmtFinSF1        1.425230
1stFlrSF          1.469604
WoodDeckSF        1.842433
OpenPorchSF       2.535114
BsmtHalfBath      3.931594
ScreenPorch       3.946694
EnclosedPorch     4.003891
BsmtFinSF2        4.146143
KitchenAbvGr      4.302254
3SsnPorch        11.376065
LowQualFinSF     12.088761
LotArea          12.822431
PoolArea         16.898328
MiscVal          21.947195
dtype: float64

In [17]:
for val in col_skewness.index:
    all_data[val] = np.log1p(all_data[val])

In [18]:
all_data['YrBltAndRemod'] = all_data['YearBuilt'] + all_data['YearRemodAdd']
all_data['TotalSF'] = all_data['BsmtFinSF1'] + all_data['BsmtFinSF2'] + all_data['1stFlrSF'] + all_data['2ndFlrSF'] + all_data['TotalBsmtSF']
all_data['Total_Bathrooms'] = all_data['FullBath'] + (0.5 * all_data['HalfBath']) + all_data['BsmtFullBath'] + (0.5 * all_data['BsmtHalfBath'])
all_data['Total_porch_sf'] = all_data['OpenPorchSF'] + all_data['3SsnPorch'] + all_data['EnclosedPorch'] + all_data['ScreenPorch'] + all_data['WoodDeckSF']
all_data['haspool'] = all_data['PoolArea'].apply(lambda x: 1 if x > 0 else 0)
all_data['has2ndfloor'] = all_data['2ndFlrSF'].apply(lambda x: 1 if x > 0 else 0)
all_data['hasgarage'] = all_data['GarageArea'].apply(lambda x: 1 if x > 0 else 0)
all_data['hasbsmt'] = all_data['TotalBsmtSF'].apply(lambda x: 1 if x > 0 else 0)
all_data['hasfireplace'] = all_data['Fireplaces'].apply(lambda x: 1 if x > 0 else 0)

In [19]:
#convert categorical variable into dummy variables
all_data = pd.get_dummies(all_data) 
all_data.head()

   MSSubClass   LotArea  ...  SaleCondition_Normal  SaleCondition_Partial
0    4.110874  9.042040  ...                     1                      0
1    3.044522  9.169623  ...                     1                      0
2    4.110874  9.328212  ...                     1                      0
3    4.262680  9.164401  ...                     0                      0
4    4.110874  9.565284  ...                     1                      0

[5 rows x 227 columns]

In [20]:
X_train = all_data[:len(Y_train)]
X_test = all_data[len(Y_train):]
print("Train size: ", X_train.shape)
print("Test size: ", X_test.shape)

Train size:  (1460, 227)
Test size:  (1459, 227)

In [ ]:
!pip install --upgrade mlxtend

In [51]:
from sklearn.linear_model import ElasticNetCV, LassoCV, RidgeCV
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import KFold
from mlxtend.regressor import StackingCVRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

kfolds = KFold(n_splits=10, shuffle=True, random_state=42)
e_alphas = [0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007]
e_l1ratio = [0.8, 0.85, 0.9, 0.95, 0.99, 1]
ridge = make_pipeline(RobustScaler(), RidgeCV(alphas=[14.5], cv=kfolds))
lasso = make_pipeline(RobustScaler(), LassoCV(max_iter=1e7, alphas=[0.0007], random_state=42, cv=kfolds))
elasticnet = make_pipeline(RobustScaler(), ElasticNetCV(max_iter=1e7, alphas=e_alphas, cv=kfolds, l1_ratio=e_l1ratio))                                
svr = make_pipeline(RobustScaler(), SVR(C= 20, epsilon= 0.008, gamma=0.0003,))
gbr = GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05, max_depth=4, max_features='sqrt', 
                                min_samples_leaf=15, min_samples_split=10, loss='huber', random_state =42)       
lightgbm = LGBMRegressor(objective='regression', num_leaves=4, learning_rate=0.01, n_estimators=5000,
                        max_bin=200, bagging_fraction=0.75, bagging_freq=5, bagging_seed=7,
                        feature_fraction=0.2, feature_fraction_seed=7, verbose=-1)
xgboost = XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, learning_rate=0.05, max_depth=3, 
                            min_child_weight=1.7817, n_estimators=2200, reg_alpha=0.4640, reg_lambda=0.8571,
                            subsample=0.5213, random_state =7, nthread = -1, objective ='reg:squarederror')
stack_gen = StackingCVRegressor(regressors=(ridge, lasso, elasticnet, gbr, xgboost, lightgbm),
                                meta_regressor=xgboost, random_state=100, use_features_in_secondary=True, n_jobs=-1)
stack_gen_model = stack_gen.fit(np.array(X_train), np.array(Y_train))
print('Stack_gen score:', stack_gen_model.score(np.array(X_train), np.array(Y_train)))
elastic_model_full_data = elasticnet.fit(X_train, Y_train)
print('Elasticnet score:', elastic_model_full_data.score(X_train, Y_train))
lasso_model_full_data = lasso.fit(X_train, Y_train)
print('Lasso score:', lasso_model_full_data.score(X_train, Y_train))
ridge_model_full_data = ridge.fit(X_train, Y_train)
print('Ridge score:', ridge_model_full_data.score(X_train, Y_train))
svr_model_full_data = svr.fit(X_train, Y_train)
print('Svr score:', svr_model_full_data.score(X_train, Y_train))
gbr_model_full_data = gbr.fit(X_train, Y_train)
print('GradientBoosting score:', gbr_model_full_data.score(X_train, Y_train))
xgb_model_full_data = xgboost.fit(X_train, Y_train)
print('Xgboost score:', xgb_model_full_data.score(X_train, Y_train))
lgb_model_full_data = lightgbm.fit(X_train, Y_train)
print('Lightgbm score:', lgb_model_full_data.score(X_train, Y_train))

Stack_gen score: 0.969909750027946
Elasticnet score: 0.929942250628558
Lasso score: 0.9214156738358945
Ridge score: 0.9243991341251506
Svr score: 0.9194852394315128
GradientBoosting score: 0.9818929231054587
Xgboost score: 0.9597895472240828
Lightgbm score: 0.9581417178985315

In [58]:
def blending_models(X):
    return ((0.1 * elastic_model_full_data.predict(X)) + \
            (0.05 * lasso_model_full_data.predict(X)) + \
            (0.1 * ridge_model_full_data.predict(X)) + \
            (0.05 * svr_model_full_data.predict(X)) + \
            (0.2 * gbr_model_full_data.predict(X)) + \
            (0.1 * xgb_model_full_data.predict(X)) + \
            (0.1 * lgb_model_full_data.predict(X)) + \
            (0.3 * stack_gen_model.predict(np.array(X))))
y_predict = np.floor(np.expm1(blending_models(X_test)))
y_predict

array([120598., 161216., 183812., ..., 170020., 119371., 221489.])

In [57]:
submission_file = pd.DataFrame({'Id':test_df['Id'], 'SalePrice':y_predict})
submission_file.to_csv('submission.csv', index=False)

In [ ]:
#best score: 0.969909750027946
#best array prediction: array([120598., 161216., 183812., ..., 170020., 119371., 221489.])